name: study_buddies
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0+1

environment:
  sdk: ^3.5.0

dependencies:
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_ui_oauth_google: ^1.4.0
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.8
  go_router: ^14.2.7
  google_sign_in: ^6.2.1
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
