// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYzFlzxwKBpcqHIgsFfEnRn2cZuhZ5fZQ',
    appId: '1:1001326048718:web:aae0a05df26c68e7f8a79f',
    messagingSenderId: '1001326048718',
    projectId: 'studybuddies-10b69',
    authDomain: 'studybuddies-10b69.firebaseapp.com',
    storageBucket: 'studybuddies-10b69.appspot.com',
    measurementId: 'G-F17WPJ6L1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCInE_p46Ac6MVmFFs3VNpj7aF1y5SE7HI',
    appId: '1:1001326048718:android:2e60c71aacae5056f8a79f',
    messagingSenderId: '1001326048718',
    projectId: 'studybuddies-10b69',
    storageBucket: 'studybuddies-10b69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT3wyH58zWO42JWsRyGht-R5PxsHdlPxg',
    appId: '1:1001326048718:ios:ec0b520cabff007ef8a79f',
    messagingSenderId: '1001326048718',
    projectId: 'studybuddies-10b69',
    storageBucket: 'studybuddies-10b69.appspot.com',
    iosBundleId: 'com.example.studyBuddies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT3wyH58zWO42JWsRyGht-R5PxsHdlPxg',
    appId: '1:1001326048718:ios:ec0b520cabff007ef8a79f',
    messagingSenderId: '1001326048718',
    projectId: 'studybuddies-10b69',
    storageBucket: 'studybuddies-10b69.appspot.com',
    iosBundleId: 'com.example.studyBuddies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYzFlzxwKBpcqHIgsFfEnRn2cZuhZ5fZQ',
    appId: '1:1001326048718:web:0dd5266422bdae4ef8a79f',
    messagingSenderId: '1001326048718',
    projectId: 'studybuddies-10b69',
    authDomain: 'studybuddies-10b69.firebaseapp.com',
    storageBucket: 'studybuddies-10b69.appspot.com',
    measurementId: 'G-EER5FYQVW1',
  );
}
